blank_issues_enabled: true
contact_links:
  - name: "Blank Issue Template"
    url: https://github.com/paramiko/paramiko/issues/new
    about: "Use this as a last resort, if none of the other issue types fit."